# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_number', models.IntegerField(verbose_name='falta')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'absence',
                'verbose_name': 'falta',
                'verbose_name_plural': 'faltas',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='rua')),
                ('number', models.IntegerField(verbose_name='n\xfamero')),
                ('district', models.CharField(max_length=200, verbose_name='bairro')),
                ('city', models.CharField(max_length=200, verbose_name='cidade')),
                ('state', models.CharField(max_length=200, verbose_name='estado')),
                ('postal_code', models.CharField(max_length=200, verbose_name='cep')),
                ('complement', models.CharField(max_length=200, verbose_name='complemento')),
                ('external_code', models.CharField(max_length=200, verbose_name='c\xf3digo externo')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'address',
                'verbose_name': 'endere\xe7o',
                'verbose_name_plural': 'endere\xe7os',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('initials', models.CharField(max_length=14, verbose_name='sigla')),
                ('external_code', models.CharField(max_length=200, verbose_name='c\xf3digo externo')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='mensagem')),
                ('status', models.IntegerField()),
                ('initial_absence_number', models.IntegerField()),
                ('final_absence_number', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Absence')),
            ],
            options={
                'db_table': 'dispute',
                'verbose_name': 'contesta\xe7\xe3o',
                'verbose_name_plural': 'contesta\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='ano')),
                ('day_period', models.IntegerField(verbose_name='per\xedodo')),
                ('semester', models.IntegerField(verbose_name='semestre')),
                ('start_at', models.DateField(verbose_name='data de in\xedcio')),
                ('end_at', models.DateField(verbose_name='data de fim')),
                ('external_code', models.CharField(max_length=200, verbose_name='c\xf3digo externo')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group',
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('register', models.CharField(max_length=14, verbose_name='cnpj')),
                ('api_token', models.CharField(max_length=50, verbose_name='TOKEN')),
                ('external_code', models.CharField(max_length=200, verbose_name='c\xf3digo externo')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'institution',
                'verbose_name': 'institui\xe7\xe3o',
                'verbose_name_plural': 'institui\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('workload', models.IntegerField(verbose_name='aula')),
                ('is_deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Group')),
            ],
            options={
                'db_table': 'lecture',
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('social_security_number', models.CharField(max_length=200, verbose_name='cpf')),
                ('register', models.CharField(max_length=200, verbose_name='matr\xedcula')),
                ('external_code', models.CharField(max_length=200, verbose_name='c\xf3digo externo')),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'person',
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('initials', models.CharField(max_length=14, verbose_name='sigla')),
                ('workload', models.IntegerField(verbose_name='carga hor\xe1ria')),
                ('external_code', models.CharField(max_length=200, verbose_name='c\xf3digo externo')),
                ('is_deleted', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(related_name='contained_subjects', to='inclass_server.Course')),
            ],
            options={
                'db_table': 'subject',
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('is_deleted', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='owned_user_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_type',
                'verbose_name': 'tipo de usu\xe1rio',
                'verbose_name_plural': 'tipos de usu\xe1rio',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='instructors',
            field=models.ManyToManyField(db_column='instructors', related_name='instructor_in_groups', to='inclass_server.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(db_column='students', related_name='member_in_groups', to='inclass_server.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Institution'),
        ),
        migrations.AddField(
            model_name='address',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Institution'),
        ),
        migrations.AddField(
            model_name='absence',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Lecture'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Person'),
        ),
    ]
