# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclass_server', '0002_auto_20180626_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
