# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclass_server', '0004_group_sunday'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inclass_server.Course'),
            preserve_default=False,
        ),
    ]
